name: Deploy Travel Management System

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      CLIENT_URL: ${{ secrets.CLIENT_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      - name: Lint and build server
        working-directory: ./server
        run: |
          npm run lint
          npm run build || echo "Skip build if not defined"

      - name: Install frontend dependencies
        working-directory: ./client
        run: npm install

      - name: Build frontend
        working-directory: ./client
        run: npm run build

      - name: Deploy (example using Heroku CLI)
        run: echo "Add your deployment step here (e.g., rsync, scp, Docker, or Heroku/GitHub Pages)"

